name: dart_rss
version: 2.0.1-breez
description: dart-rss is a rss parser for RSS1.0/RSS2.0/Atom. It also support Dublin-Core, Content, Syndication additional modules. This libary is forked from webfeed(https://github.com/witochandra/webfeed).
homepage: https://github.com/sudame/dart-rss
environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: 3.0.0

dependencies:
  xml: ^6.1.0
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  lints: ^2.0.0
  test: any

